// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB125eXti6c8VwuaSYprM_c8UyNX1ljJXA',
    appId: '1:649547460716:web:37cb26a2678ade2bc56849',
    messagingSenderId: '649547460716',
    projectId: 'telecom-sih',
    authDomain: 'telecom-sih.firebaseapp.com',
    storageBucket: 'telecom-sih.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB125eXti6c8VwuaSYprM_c8UyNX1ljJXA',
    appId: '1:649547460716:android:37cb26a2678ade2bc56849',
    messagingSenderId: '649547460716',
    projectId: 'telecom-sih',
    storageBucket: 'telecom-sih.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB125eXti6c8VwuaSYprM_c8UyNX1ljJXA',
    appId: '1:649547460716:ios:37cb26a2678ade2bc56849',
    messagingSenderId: '649547460716',
    projectId: 'telecom-sih',
    storageBucket: 'telecom-sih.firebasestorage.app',
    iosBundleId: 'com.sih.telecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB125eXti6c8VwuaSYprM_c8UyNX1ljJXA',
    appId: '1:649547460716:ios:37cb26a2678ade2bc56849',
    messagingSenderId: '649547460716',
    projectId: 'telecom-sih',
    storageBucket: 'telecom-sih.firebasestorage.app',
    iosBundleId: 'com.sih.telecom',
  );
}